package ui;

import conexiones.Conexion;
import domain.Usuario;
import domain.UsuarioDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author briza
 */
public class ASIGNAR extends javax.swing.JFrame {

    Usuario usuario;
    int idSelec = 0;
    String descripcion = "";

    public ASIGNAR() {
        initComponents();
    }

    public ASIGNAR(Usuario user) {
        initComponents();
        this.usuario = user;
        desTarea.setText("");
        cargar();
        setLocationRelativeTo(null);
        nombreuser.setText("Usuario: " + usuario.getUsuario().toUpperCase());
        tipouser.setText("Tipo usuario: " + usuario.getNombre_tipo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        desTarea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        infUsuario = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nombreuser = new javax.swing.JLabel();
        tipouser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(743, 424));
        setMinimumSize(new java.awt.Dimension(743, 424));
        setPreferredSize(new java.awt.Dimension(743, 424));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel2.setText("ASIGNACION DE TAREAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 679, 51));

        jLabel1.setText("Nombre de la tarea:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 71, 114, -1));

        desTarea.setText(" ");
        getContentPane().add(desTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 68, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Seleccione el usuario a quien va asignar la tarea:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 310, -1));

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Usuario", "Puesto"
            }
        ));
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaUsuarios);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 530, 120));

        infUsuario.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        infUsuario.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(infUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 180, 20));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 80, 30));

        jLabel6.setText("SESION ACTIVA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 165, -1));
        getContentPane().add(nombreuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 124, 21));
        getContentPane().add(tipouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 165, 21));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public final void cargar() {
        DefaultTableModel modelo = (DefaultTableModel) TablaUsuarios.getModel();
        modelo.setRowCount(0);
        UsuarioDAO user = new UsuarioDAO();
        user.verSubs(usuario, modelo);
    }

    public void addTarea() {
        UsuarioDAO user = new UsuarioDAO();
        if (user.asignarTarea(descripcion, idSelec)) {
            JOptionPane.showConfirmDialog(null, "Tarea asignada Exitosamente", "Ejecución correcta", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            desTarea.setText("");
            descripcion = "";
        } else {
            JOptionPane.showConfirmDialog(null, "Algo salio mal", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        int seleccionar = TablaUsuarios.rowAtPoint(evt.getPoint());
        String aux = String.valueOf(TablaUsuarios.getValueAt(seleccionar, 0));
        idSelec = Integer.parseInt(aux);
        infUsuario.setText("Seleccionado: " + String.valueOf(TablaUsuarios.getValueAt(seleccionar, 2)));
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        descripcion = desTarea.getText();
        if (descripcion.equals("")) {
            JOptionPane.showConfirmDialog(null, "Ingrese descripcion", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
        } else if (idSelec == 0) {
            JOptionPane.showConfirmDialog(null, "Seleccione un usuario", "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
        } else {
            addTarea();
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        MENU m = new MENU(usuario);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASIGNAR.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASIGNAR.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASIGNAR.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASIGNAR.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASIGNAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JTextField desTarea;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel infUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombreuser;
    private javax.swing.JLabel tipouser;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
