package ui;

import domain.IndiceMax;
import domain.MDepartamentos;
import domain.MUsuarios;
import domain.Usuario;
import domain.UsuarioDAO;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author briza
 */
public class CONSULTAS extends javax.swing.JFrame {

    /**
     * Creates new form CONSULTAS
     */
    Usuario usuario;
    int idSelec = 0;
    String descripcion = "";

    public CONSULTAS() {
        initComponents();
    }

    public CONSULTAS(Usuario user) {
        initComponents();
        this.usuario = user;
        setLocationRelativeTo(null);
        habilitarPermisos();
        cargarComboBox();
        PANEL1.setVisible(true);
        PANEL2.setVisible(false);
        PANEL3.setVisible(false);
        PANEL4.setVisible(false);
        nombreuser.setText("Usuario: " + usuario.getUsuario().toUpperCase());
        tipouser.setText("Tipo usuario: " + usuario.getNombre_tipo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tipouser = new javax.swing.JLabel();
        bconsultadepa = new javax.swing.JButton();
        bconsultausuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboUsuarios = new javax.swing.JComboBox<>();
        comboDepas = new javax.swing.JComboBox<>();
        volver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboMax = new javax.swing.JComboBox<>();
        bconsultamayor = new javax.swing.JButton();
        mistareas = new javax.swing.JButton();
        mAnuncioTareas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreuser = new javax.swing.JLabel();
        tareaspordia = new javax.swing.JButton();
        tareaspormes = new javax.swing.JButton();
        PANEL1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();
        PANEL2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMax = new javax.swing.JTable();
        PANEL3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        matrizpordias = new javax.swing.JTable();
        PANEL4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        matrizpormes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(974, 700));
        setMinimumSize(new java.awt.Dimension(974, 700));
        setPreferredSize(new java.awt.Dimension(974, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel2.setText("CONSULTA DE TAREAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 532, 51));
        getContentPane().add(tipouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 165, 21));

        bconsultadepa.setText("CONSULTA POR DEPARTAMENTO");
        bconsultadepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconsultadepaActionPerformed(evt);
            }
        });
        getContentPane().add(bconsultadepa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        bconsultausuario.setText("CONSULTA POR USUARIO");
        bconsultausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconsultausuarioActionPerformed(evt);
            }
        });
        getContentPane().add(bconsultausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 199, -1));

        jLabel1.setText("Seleccione el departamento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, -1));

        jLabel3.setText("Seleccione el usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));

        comboUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione usuario" }));
        comboUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboUsuariosItemStateChanged(evt);
            }
        });
        getContentPane().add(comboUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 164, -1));

        comboDepas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione departamento" }));
        comboDepas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDepasItemStateChanged(evt);
            }
        });
        getContentPane().add(comboDepas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 164, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 80, 30));

        jLabel4.setText("Usuario con mas tareas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        comboMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione filtro", "tareas asignadas", "tareas vencidas" }));
        comboMax.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMaxItemStateChanged(evt);
            }
        });
        getContentPane().add(comboMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 164, -1));

        bconsultamayor.setText("CONSULTA POR EL MAYOR");
        bconsultamayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconsultamayorActionPerformed(evt);
            }
        });
        getContentPane().add(bconsultamayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 199, -1));

        mistareas.setText("MIS TAREAS");
        mistareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mistareasActionPerformed(evt);
            }
        });
        getContentPane().add(mistareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 199, -1));

        mAnuncioTareas.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        mAnuncioTareas.setForeground(new java.awt.Color(0, 0, 255));
        mAnuncioTareas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mAnuncioTareas.setText("TAREAS ENCONTRADAS");
        getContentPane().add(mAnuncioTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 900, -1));

        jLabel6.setText("SESION ACTIVA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 165, -1));
        getContentPane().add(nombreuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 124, 21));

        tareaspordia.setText("TAREAS POR DIA");
        tareaspordia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tareaspordiaActionPerformed(evt);
            }
        });
        getContentPane().add(tareaspordia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 190, 30));

        tareaspormes.setText("TAREAS FINALIZADAS POR MES");
        tareaspormes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tareaspormesActionPerformed(evt);
            }
        });
        getContentPane().add(tareaspormes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 220, -1));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(750, 350));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(750, 350));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(750, 300));

        tablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID TAREA", "DESCRIPCION", "USUARIO", "FECHA DE ASIGNACION", "ESTADO"
            }
        ));
        tablaTareas.setMaximumSize(new java.awt.Dimension(800, 240));
        tablaTareas.setMinimumSize(new java.awt.Dimension(800, 240));
        tablaTareas.setPreferredSize(new java.awt.Dimension(800, 300));
        jScrollPane1.setViewportView(tablaTareas);

        PANEL1.add(jScrollPane1);

        getContentPane().add(PANEL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 890, 320));

        tablaMax.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID USUARIO", "USUARIO", "CANTIDAD TAREAS"
            }
        ));
        tablaMax.setMinimumSize(new java.awt.Dimension(800, 170));
        tablaMax.setOpaque(false);
        tablaMax.setPreferredSize(new java.awt.Dimension(800, 170));
        jScrollPane2.setViewportView(tablaMax);

        PANEL2.add(jScrollPane2);

        getContentPane().add(PANEL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 270, 780, 170));

        jScrollPane3.setMinimumSize(new java.awt.Dimension(800, 170));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(800, 170));

        matrizpordias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID USUARIO", "USUARIO", "DEPARTAMENTO", "HACE 1 DIAS", "HACE 2 DIAS", "HACE 3 DIAS", "HACE 4 DIAS", "HACE 5 DIAS"
            }
        ));
        matrizpordias.setMaximumSize(new java.awt.Dimension(930, 170));
        matrizpordias.setMinimumSize(new java.awt.Dimension(930, 170));
        matrizpordias.setPreferredSize(new java.awt.Dimension(930, 170));
        jScrollPane3.setViewportView(matrizpordias);
        if (matrizpordias.getColumnModel().getColumnCount() > 0) {
            matrizpordias.getColumnModel().getColumn(6).setHeaderValue("HACE 4 DIAS");
            matrizpordias.getColumnModel().getColumn(7).setResizable(false);
            matrizpordias.getColumnModel().getColumn(7).setHeaderValue("HACE 5 DIAS");
        }

        PANEL3.add(jScrollPane3);

        getContentPane().add(PANEL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 940, 170));

        jScrollPane4.setMinimumSize(new java.awt.Dimension(800, 170));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(800, 170));

        matrizpormes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID USUARIO", "USUARIO", "DEPARTAMENTO", "HACE 1 MES", "HACE 2 MESES", "HACE 3 MESES"
            }
        ));
        matrizpormes.setMaximumSize(new java.awt.Dimension(930, 170));
        matrizpormes.setMinimumSize(new java.awt.Dimension(930, 170));
        matrizpormes.setPreferredSize(new java.awt.Dimension(930, 170));
        jScrollPane4.setViewportView(matrizpormes);

        PANEL4.add(jScrollPane4);

        getContentPane().add(PANEL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 940, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarMisTareas() {
        DefaultTableModel modelo = (DefaultTableModel) tablaTareas.getModel();
        modelo.setRowCount(0);
        UsuarioDAO user = new UsuarioDAO();
        user.misTareas(1, usuario.getId_usuario(), modelo);
    }

    public final void habilitarPermisos() {
        if (usuario.getId_tipo() != 1) {
            if (usuario.getId_tipo() == 3) {
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                comboUsuarios.setVisible(false);
                comboMax.setVisible(false);
                bconsultausuario.setVisible(false);
                bconsultamayor.setVisible(false);
            }
            jLabel1.setVisible(false);
            comboDepas.setVisible(false);
            bconsultadepa.setVisible(false);
            jLabel4.setVisible(false);
            comboMax.setVisible(false);
            bconsultamayor.setVisible(false);
        }
        comboDepas.setEnabled(false);
        comboUsuarios.setEnabled(false);
        comboMax.setEnabled(false);
    }

    public final void cargarComboBox() {
        //cargar al combo box de departamentos
        MDepartamentos dep = new MDepartamentos();
        DefaultComboBoxModel modeloDep = new DefaultComboBoxModel(dep.mostrarDepas());
        comboDepas.setModel(modeloDep);

        //cargar al combo box de usuarios
        MUsuarios u = new MUsuarios();
        DefaultComboBoxModel modeloUs = new DefaultComboBoxModel(u.mostrarUsuarios(usuario.getId_tipo(), usuario.getId_departamento()));
        comboUsuarios.setModel(modeloUs);

        //cargar al combo box de Maximos
        IndiceMax in = new IndiceMax();
        DefaultComboBoxModel modeloIn = new DefaultComboBoxModel(in.mostrarIndices());
        comboMax.setModel(modeloIn);
    }

    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaTareas.getModel();
        modelo.setRowCount(0);
    }
    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        MENU m = new MENU(usuario);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void bconsultadepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconsultadepaActionPerformed
        limpiarTabla();
        cargarComboBox();
        comboDepas.setEnabled(true);
        comboUsuarios.setEnabled(false);
        comboMax.setEnabled(false);
        PANEL1.setVisible(true);
        PANEL2.setVisible(false);
        PANEL3.setVisible(false);
        PANEL4.setVisible(false);
        mAnuncioTareas.setText("TAREAS ENCONTRADAS");
    }//GEN-LAST:event_bconsultadepaActionPerformed

    private void bconsultausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconsultausuarioActionPerformed
        limpiarTabla();
        cargarComboBox();
        comboDepas.setEnabled(false);
        comboUsuarios.setEnabled(true);
        comboMax.setEnabled(false);
        PANEL1.setVisible(true);
        PANEL2.setVisible(false);
        PANEL3.setVisible(false);
        PANEL4.setVisible(false);
        mAnuncioTareas.setText("TAREAS ENCONTRADAS");
    }//GEN-LAST:event_bconsultausuarioActionPerformed

    private void bconsultamayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconsultamayorActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaMax.getModel();
        modelo.setRowCount(0);
        limpiarTabla();
        cargarComboBox();
        comboDepas.setEnabled(false);
        comboUsuarios.setEnabled(false);
        comboMax.setEnabled(true);
        PANEL2.setVisible(true);
        PANEL1.setVisible(false);
        PANEL3.setVisible(false);
        PANEL4.setVisible(false);
        mAnuncioTareas.setText("");
    }//GEN-LAST:event_bconsultamayorActionPerformed

    private void mistareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mistareasActionPerformed
        comboDepas.setEnabled(false);
        comboUsuarios.setEnabled(false);
        comboMax.setEnabled(false);
        cargarComboBox();
        cargarMisTareas();
        PANEL1.setVisible(true);
        PANEL2.setVisible(false);
        PANEL3.setVisible(false);
        mAnuncioTareas.setText("TAREAS ENCONTRADAS");
    }//GEN-LAST:event_mistareasActionPerformed

    private void comboDepasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDepasItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            MDepartamentos dep = (MDepartamentos) comboDepas.getSelectedItem();
            DefaultTableModel modelo = (DefaultTableModel) tablaTareas.getModel();
            modelo.setRowCount(0);
            UsuarioDAO user = new UsuarioDAO();
            user.verTareasDepartamento(dep.getId(), 1, modelo);
        }
    }//GEN-LAST:event_comboDepasItemStateChanged

    private void comboUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboUsuariosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            MUsuarios us = (MUsuarios) comboUsuarios.getSelectedItem();
            DefaultTableModel modelo = (DefaultTableModel) tablaTareas.getModel();
            modelo.setRowCount(0);
            UsuarioDAO user = new UsuarioDAO();
            user.misTareas(1, us.getId(), modelo);
        }
    }//GEN-LAST:event_comboUsuariosItemStateChanged

    private void comboMaxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMaxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            DefaultTableModel modelo = (DefaultTableModel) tablaMax.getModel();
            modelo.setRowCount(0);
            UsuarioDAO user = new UsuarioDAO();
            int id = comboMax.getSelectedIndex();
            user.busquedaMayor(id, modelo);
            if (id == 1) {
                mAnuncioTareas.setText("USUARIO QUE TIENE MAS TAREAS ASIGNADAS Y EN ESTADO ACTIVA");
            } else if (id == 2) {
                mAnuncioTareas.setText("USUARIO QUE TIENE MAS TAREAS VENCIDAS (TAREAS EN ESTADO ACTIVA Y FECHA DE ASIGNACION MAYOR A 15 DIAS)");
            }
        }
    }//GEN-LAST:event_comboMaxItemStateChanged

    private void tareaspordiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tareaspordiaActionPerformed
        cargarComboBox();
        PANEL1.setVisible(false);
        PANEL2.setVisible(false);
        PANEL4.setVisible(false);
        PANEL3.setVisible(true);
        comboDepas.setEnabled(false);
        comboUsuarios.setEnabled(false);
        comboMax.setEnabled(false);
        mAnuncioTareas.setText("CANTIDAD DE TAREAS ASIGNADAS POR DIA (ULIMOS 5 DIAS)");
        DefaultTableModel modelo = (DefaultTableModel) matrizpordias.getModel();
        modelo.setRowCount(0);
        UsuarioDAO user = new UsuarioDAO();
        user.verTareasUltimosDias(usuario, modelo);
    }//GEN-LAST:event_tareaspordiaActionPerformed

    private void tareaspormesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tareaspormesActionPerformed
        cargarComboBox();
        PANEL1.setVisible(false);
        PANEL2.setVisible(false);
        PANEL3.setVisible(false);
        PANEL4.setVisible(true);
        comboDepas.setEnabled(false);
        comboUsuarios.setEnabled(false);
        comboMax.setEnabled(false);
        mAnuncioTareas.setText("CANTIDAD DE TAREAS FINALIZADAS POR MES (ULTIMOS 3 MESES)");
        DefaultTableModel modelo = (DefaultTableModel) matrizpormes.getModel();
        modelo.setRowCount(0);
        UsuarioDAO user = new UsuarioDAO();
        user.verTareasFinalizasPorMes(usuario, modelo);
    }//GEN-LAST:event_tareaspormesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONSULTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONSULTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONSULTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONSULTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONSULTAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL1;
    private javax.swing.JPanel PANEL2;
    private javax.swing.JPanel PANEL3;
    private javax.swing.JPanel PANEL4;
    private javax.swing.JButton bconsultadepa;
    private javax.swing.JButton bconsultamayor;
    private javax.swing.JButton bconsultausuario;
    private javax.swing.JComboBox<String> comboDepas;
    private javax.swing.JComboBox<String> comboMax;
    private javax.swing.JComboBox<String> comboUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel mAnuncioTareas;
    private javax.swing.JTable matrizpordias;
    private javax.swing.JTable matrizpormes;
    private javax.swing.JButton mistareas;
    private javax.swing.JLabel nombreuser;
    private javax.swing.JTable tablaMax;
    private javax.swing.JTable tablaTareas;
    private javax.swing.JButton tareaspordia;
    private javax.swing.JButton tareaspormes;
    private javax.swing.JLabel tipouser;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
