/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import conexiones.*;
import static conexiones.Conexion.*;
import domain.Usuario;
import domain.UsuarioDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fer
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        this.icono = new ImageIcon(getClass().getResource("/imagenes/ok.png"));
        initComponents();
        setLocationRelativeTo(null);
        transparenciaButton();
    }

    Icon icono;
    Usuario usuario = new Usuario();
    Conexion conexion = new Conexion();

    public void useOracleSql() {
        Connection conn = null;
        usuario.setUsuario(ingreso_user.getText());
        usuario.setContraseña(ingreso_pass.getText());
        try {
            conn = conexion.getConnection();
            UsuarioDAO user = new UsuarioDAO(conn);
            if (user.seleccionar(usuario) != false) {
                JOptionPane.showConfirmDialog(null, "Bienvenido " + ingreso_user.getText() + "\nTipo Usuario: " + usuario.getNombre_tipo(), "Acceso Correcto", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE, icono);
                ingreso_user.setText("");
                ingreso_pass.setText("");
                ingreso_user.requestFocus();
                MENU m = new MENU(usuario);
                m.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showConfirmDialog(null, "Usuario o contraseña incorrecto", "Acceso Denegado", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                ingreso_user.setText("");
                ingreso_pass.setText("");
                ingreso_user.requestFocus();
            }
        } catch (Exception ex) {
            ex.printStackTrace(System.out);
        } finally {
            try {
                Conexion.close(conn);
            } catch (SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fb1 = new javax.swing.JLabel();
        fb2 = new javax.swing.JLabel();
        ingreso_pass = new javax.swing.JPasswordField();
        pass = new javax.swing.JLabel();
        ingreso_user = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresar.setBackground(new java.awt.Color(0, 0, 153));
        ingresar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 30));

        salir.setBackground(new java.awt.Color(0, 0, 153));
        salir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 30));

        fb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Botton.png"))); // NOI18N
        getContentPane().add(fb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 30));

        fb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Botton.png"))); // NOI18N
        getContentPane().add(fb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 30));

        ingreso_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_passActionPerformed(evt);
            }
        });
        getContentPane().add(ingreso_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, 30));
        ingreso_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_passActionPerformed(evt);
                if (ingreso_user.getText().equalsIgnoreCase("") || ingreso_pass.getText().equalsIgnoreCase("")) {
                    JOptionPane.showMessageDialog(null, "No se aceptan campos vacios",
                        "Error de datos", JOptionPane.ERROR_MESSAGE);
                    ingreso_user.setText("");
                    ingreso_pass.setText("");
                    ingreso_user.requestFocus();
                } else {
                    //   useMySql();     //llama a la conexión implementada para MySql
                    useOracleSql(); //llama a la conexión implementada para OracleSql
                }
            }
        });

        pass.setText("Contraseña");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        ingreso_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_userActionPerformed(evt);
            }
        });
        getContentPane().add(ingreso_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 210, 30));
        ingreso_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_pass.requestFocus();
            }
        });

        user.setText("Usuario");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        login.setText("jLabel2");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 152, 150));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        if (ingreso_user.getText().equalsIgnoreCase("") || ingreso_pass.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "No se aceptan campos vacios",
                    "Error de datos", JOptionPane.ERROR_MESSAGE);
            ingreso_user.setText("");
            ingreso_pass.setText("");
            ingreso_user.requestFocus();
        } else {
            useOracleSql();
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void ingreso_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreso_passActionPerformed

    private void ingreso_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_userActionPerformed

    }//GEN-LAST:event_ingreso_userActionPerformed
    public void transparenciaButton() {
        ingresar.setOpaque(false);
        ingresar.setContentAreaFilled(false);
        ingresar.setBorderPainted(false);
        salir.setOpaque(false);
        salir.setContentAreaFilled(false);
        salir.setBorderPainted(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fb1;
    private javax.swing.JLabel fb2;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresar;
    private javax.swing.JPasswordField ingreso_pass;
    private javax.swing.JTextField ingreso_user;
    private javax.swing.JLabel login;
    private javax.swing.JLabel pass;
    private javax.swing.JButton salir;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
